#!/bin/sh
#jonmod 180514a
mkdir -p /tmp/repo2sfs/usr/bin
cat > /tmp/repo2sfs/usr/bin/chromium-puppy << EOF
#!/bin/sh
#export CHROMIUM_FLAGS="--ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=26.0.0.137"
export CHROMIUM_FLAGS="--ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so  --ppapi-flash-version=29.0.0.171"
xhost +local:puppy
#su - puppy -c "/usr/bin/chromium  --user-data-dir=/home/puppy/chromium_puppy_user_data_dir --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=26.0.0.137"
su -l puppy -c "/usr/lib/chromium/chromium --user-data-dir=/home/puppy/chromium_puppy_user_data_dir --disk-cache-dir=/home/puppy/chromium_puppy_user_cache_dir --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --disk-cache-size=10000000 --disable-translate --always-authorize-plugins --media-cache-size=10000000 \$1"
EOF
chmod 755 /tmp/repo2sfs/usr/bin/chromium-puppy

cat > /tmp/repo2sfs/usr/share/applications/chromium.desktop << EOF2
[Desktop Entry]
Version=1.0
Name=Chromium puppy -repo2sfs changes.dat
Exec=chromium-puppy
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/share/pixmaps/chromium.png
Categories=Network;
MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Chromium
StartupNotify=true
EOF2


cat > /tmp/repo2sfs/usr/bin/chromium-puppy-sda1 << EOF31
#!/bin/sh
export CHROMIUM_FLAGS="--ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so  --ppapi-flash-version=29.0.0.171"
xhost +local:puppy
mkdir -p /mnt/sda1/downloads_linux/.data/chromium
mkdir -p /mnt/sda1/downloads_linux/.cache/chromium
#su - puppy -c "/usr/bin/chromium  --user-data-dir=/home/puppy/chromium_puppy_user_data_dir --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=26.0.0.137"
su -l puppy -c "/usr/lib/chromium/chromium --user-data-dir=/mnt/sda1/downloads_linux/.data/chromium --disk-cache-dir=/mnt/sda1/downloads_linux/.cache/chromium --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --disable-translate --always-authorize-plugins --disk-cache-size=10000000 --media-cache-size=10000000 \$1"
EOF31
chmod 755 /tmp/repo2sfs/usr/bin/chromium-puppy-sda1

cat > /tmp/repo2sfs/usr/share/applications/chromium-puppy-sda1.desktop << EOF32
[Desktop Entry]
Version=1.0
Name=Chromium puppy -sda1(C:) EXTERNAL repo2sfs
Exec=chromium-puppy-sda1
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/share/pixmaps/chromium.png
Categories=Network;
MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Chromium
StartupNotify=true
EOF32




cat > /tmp/repo2sfs/usr/bin/chromium-puppy-sdb1 << EOF41
#!/bin/sh
export CHROMIUM_FLAGS="--ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so  --ppapi-flash-version=29.0.0.171"
xhost +local:puppy
mkdir -p /mnt/sdb1/downloads_linux/.data/chromium
mkdir -p /mnt/sdb1/downloads_linux/.cache/chromium
#su - puppy -c "/usr/bin/chromium  --user-data-dir=/home/puppy/chromium_puppy_user_data_dir --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=26.0.0.137"
su -l puppy -c "/usr/lib/chromium/chromium --user-data-dir=/mnt/sdb1/downloads_linux/.data/chromium --disk-cache-dir=/mnt/sdb1/downloads_linux/.cache/chromium --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --disable-translate --always-authorize-plugins --disk-cache-size=10000000 --media-cache-size=10000000 \$1"
EOF41
chmod 755 /tmp/repo2sfs/usr/bin/chromium-puppy-sdb1

cat > /tmp/repo2sfs/usr/share/applications/chromium-puppy-sdb1.desktop << EOF42
[Desktop Entry]
Version=1.0
Name=Chromium puppy -sdb1 (2nd DISK-USB) EXTERNAL repo2sfs
Exec=chromium-puppy-sdb1
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/share/pixmaps/chromium.png
Categories=Network;
MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Chromium
StartupNotify=true
EOF42

read -p "Done. Remember to create the puppy user. Press Enter: "