#!/bin/sh

chmod 755 /tmp/repo2sfs/usr/bin/opera-puppy
chmod 4755 /tmp/repo2sfs/usr/lib/x86_64-linux-gnu/opera/opera_sandbox
read -p "Done. Remember to create the puppy user. Press Enter: "


_______________________________
#!/bin/sh
#jonmod 180514a
#latest slimjet amd64 https://www.slimjetbrowser.com/release/slimjet_amd64.deb
mkdir -p /tmp/repo2sfs/usr/bin
# needs extras: libnss3 libgconf-2-4


#!/bin/sh

cat > /tmp/repo2sfs/usr/bin/opera-puppy << EOF
#!/bin/sh
#export CHROMIUM_FLAGS="--ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=26.0.0.137"
#export SLIMJET_FLAGS="--ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so  --ppapi-flash-version=29.0.0.171  --media-cache-size=10000000"
xhost +local:puppy
#sudo -u puppy /usr/bin/slimjet  --user-data-dir=/home/puppy/slimjet_puppy_user_data_dir --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=26.0.0.137"
sudo -u puppy opera --user-data-dir=/home/puppy/.data/opera_puppy_user_data_dir --disk-cache-dir=/home/puppy/.cache/opera_puppy_user_cache_dir --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so  --ppapi-flash-version=29.0.0.171 --disable-features=TranslateUI --always-authorize-plugins --media-cache-size=10000000 "\$@"
EOF
chmod 755 /tmp/repo2sfs/usr/bin/opera-puppy

cat > /tmp/repo2sfs/usr/share/applications/opera.desktop << EOF2
[Desktop Entry]
Version=1.0
Name=Opera puppy -repo2sfs changes.dat
Exec=opera-puppy
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/share/pixmaps/opera.xpm
Categories=Network;
MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Opera
StartupNotify=true
EOF2


cat > /tmp/repo2sfs/usr/bin/opera-puppy-sda1 << EOF31
#!/bin/sh

xhost +local:puppy
mkdir -p /mnt/sda1/downloads_linux/.data/opera
mkdir -p /mnt/sda1/downloads_linux/.cache/opera
#sudo -u puppy /usr/bin/slimjet  --user-data-dir=/home/puppy/slimjet_puppy_user_data_dir --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=26.0.0.137"
sudo -u puppy opera --user-data-dir=/mnt/sda1/downloads_linux/.data/opera --disk-cache-dir=/mnt/sda1/downloads_linux/.cache/opera --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --disable-features=TranslateUI --always-authorize-plugins  --ppapi-flash-version=29.0.0.171 "\$@"
EOF31
chmod 755 /tmp/repo2sfs/usr/bin/opera-puppy-sda1

cat > /tmp/repo2sfs/usr/share/applications/opera-puppy-sda1.desktop << EOF32
[Desktop Entry]
Version=1.0
Name=Opera puppy -sda1(C:) EXTERNAL repo2sfs
Exec=opera-puppy-sda1
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/share/pixmaps/opera.xpm
Categories=Network;
MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Opera
StartupNotify=true
EOF32




cat > /tmp/repo2sfs/usr/bin/opera-puppy-sdb1 << EOF41
#!/bin/sh

xhost +local:puppy
mkdir -p /mnt/sdb1/downloads_linux/.data/opera
mkdir -p /mnt/sdb1/downloads_linux/.cache/opera
#sudo -u puppy /usr/bin/slimjet  --user-data-dir=/home/puppy/slimjet_puppy_user_data_dir --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=26.0.0.137"
sudo -u puppy opera --user-data-dir=/mnt/sdb1/downloads_linux/.data/opera --disk-cache-dir=/mnt/sdb1/downloads_linux/.cache/opera --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --disable-features=TranslateUI --always-authorize-plugins  --ppapi-flash-version=29.0.0.171 "\$@"
EOF41
chmod 755 /tmp/repo2sfs/usr/bin/opera-puppy-sdb1

cat > /tmp/repo2sfs/usr/share/applications/opera-puppy-sdb1.desktop << EOF42
[Desktop Entry]
Version=1.0
Name=Opera puppy -sdb1 (2nd DISK-USB) EXTERNAL repo2sfs
Exec=opera-puppy-sdb1
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/share/pixmaps/opera.xpm
Categories=Network;
MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Opera
StartupNotify=true
EOF42

read -p "Done. Remember to create the puppy user. Press Enter: "