#!/bin/sh

cat > /tmp/repo2sfs/usr/bin/chromium-puppy << EOF
#!/bin/sh
xhost +local:puppy
su -l puppy -c "/usr/lib/chromium/chromium --user-data-dir=/home/puppy/chrome/user --disk-cache-dir=/home/puppy/chrome/cache --disk-cache-size=10000000 --media-cache-size=10000000 \$1"
EOF
chmod 755 /tmp/repo2sfs/usr/bin/chromium-puppy

cat > /tmp/repo2sfs/usr/share/applications/chromium.desktop << EOF2
[Desktop Entry]
Version=1.0
Name=Chromium
Exec=chromium-puppy
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/share/pixmaps/chromium.png
Categories=Network;
MimeType=text/html;text/xml;application/xhtml_xml;x-scheme-handler/http;x-scheme-handler/https;
StartupWMClass=Chromium
StartupNotify=true
EOF2

read -p "Done. Remember to create the puppy user. Press Enter: "
